# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9366604ae1fd410a3fa95a7bcddd6128158030e33a6392b532e24891c94077b2cc1f02c9efc672d9341a78caec76b47d34179f221197d13541530dcac1e488ce

test:
  secret_key_base: e20deaef24fbec2f379f94aa2667647b92448feb5203449cd77e89f51a38ca9e23cb678736cc5f9c315508eb6c155c1060ccbfe49ac70f1ba9f030ddf7310cb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
